const countries = {
    AF:	"Afghanistan",
    AL:	"Algeria",
    AD:	"Andorra",
    AO:	"Angola",
    AI:	"Anguilla",
    AQ:	'Antarctica',
    AR:	'Argentina',
    AM:	'Armenia',
    AW:	'Aruba',
    AU:	'Australia',
    AT:	'Austria',
    AZ:	'Bahamas',
    BH:	"Bahrain",
    BD:	'Bangladesh',
    BB:	'Barbados',
    BY:	'Belarus',
    BE:	'Belgium',
    BZ:	'Belize',
    BJ:	'Benin',
    BM:	'Bermuda',
    BT:	'Bhutan',
    BO:	'Bolivia',
    BW:	'Botswana',
    BR:	'Brazil',
    BG:	'Bulgaria',
    BI:	'Burundi',
    KH:	'Cambodia',
    CM:	'Cameroon',
    CA:	'Canada',
    TD:	'Chad',
    CL:	'Chile',
    CN:	'China',
    CO:	'Colombia',
    CR:	'Costa Rica',
    HR:	'Croatia',
    CU:	'Cuba',
    CW:	'Curaçao',
    CY:	'Cyprus',
    CZ:	'Czech Republic',
    DK:	'Denmark',
    DM:	'Dominica',
    EC:	'Ecuador',
    EG:	'Egypt',
    SV:	'El Salvador',
    ER:	'Eritrea',
    EE:	'Estonia',
    SZ:	'Eswatini',
    ET:	'Ethiopia',
    FJ:	'Fiji',
    FI:	'Finland',
    FR:	'France',
    GF : 'Guiana',
    PF:	'Polynesia',
    GA:	'Gabon',
    GM:	'Gambia',
    GE:	'Georgia',
    DE:	'Germany',
    GH:	'Ghana',
    GI:	'Gibraltar',
    GR:	'Greece',
    GL:	'Greenland',
    GD:	'Grenada',
    GP:	'Guadeloupe',
    GU:	'Guam',
    GT:	'Guatemala',
    GN:	'Guinea',
    GY:	'Guyana',
    HT:	'Haiti',
    HN:	'Honduras',
    HK:	'Hong Kong',
    HU:	'Hungary',
    IS:	'Iceland',
    IN:	'India',
    ID:	'Indonesia',
    IR:	'Iran',
    IQ:	'Iraq',
    IE:	'Ireland',
    IL:	'Israel',
    IT:	'Italy',
    JM:	'Jamaica',
    JP:	'Japan',
    JO:	'Jordan',
    KZ:	'Kazakhstan',
    KE:	'Kenya',
    KI:	'Kiribati',
    KP:	'Korea',
    KR:	'Korea' ,
    KW:	'Kuwait',
    LV:	'Latvia',
    LB:	'Lebanon',
    LS:	'Lesotho',
    LR:	'Liberia',
    LY:	'Libya',
    LI:	'Liechtenstein',
    LT:	'Lithuania',
    LU:	'Luxembourg',
    MO:	'Macao',
    MG:	'Madagascar',
    MW:	'Malawi',
    MY:	'Malaysia',
    MV:	'Maldives',
    ML:	'Mali',
    MT:	'Malta',
    MQ:	'Martinique',
    MR:	'Mauritania',
    MU:	'Mauritius',
    YT:	'Mayotte',
    MX:	'Mexico',
    MN:	'Mongolia',
    ME:	'Montenegro',
    MS:	'Montserrat',
    MA:	'Morocco',
    MZ:	'Mozambique',
    MM:	'Myanmar',
    NA:	'Namibia',
    NR:	'Nauru',
    NP:	'Nepal',
    NL:	'Netherlands',
    NZ:	'New Zealand',
    NI:	'Nicaragua',
    NE:	'Niger',
    NG:	'Nigeria',
    NO:	'Norway',
    OM:	'Oman',
    PK:	'Pakistan',
    PW:	'Palau',
    PA:	'Panama',
    PY:	'Paraguay',
    PE:	'Peru',
    PH:	'Philippines',
    PL:	'Poland',
    PT:	'Portugal',
    PR:	'Puerto Rico',
    QA:	'Qatar',
    RO:	'Romania',
    RU:	'Russia',
    WS:	'Samoa',
    SA:	'Saudi Arabia',
    SN:	'Senegal',
    RS:	'Serbia',
    SC:	'Seychelles',
    SL:	'Sierra Leone',
    SG:	'Singapore',
    SK:	'Slovakia',
    SI:	'Slovenia',
    SO:	'Somalia',
    ES:	'Spain',
    LK:	'Sri Lanka',
    SD:	'Sudan',
    SR:	'Suriname',
    SE:	'Sweden',
    CH:	'Switzerland',
    TW:	'Taiwan',
    TH:	'Thailand',
    TV:	'Tuvalu',
    UG:	'Uganda',
    UA:	'Ukraine',
    GB:	'United Kingdom',
    US:	'United States',
    UY:	'Uruguay',
    UZ:	'Uzbekistan',
    VU:	'Vanuatu',
    VE:	'Venezuela',
    VN:	'Viet Nam',
    ZM:	'Zambia',
    ZW:	'Zimbabwe'
}

export default countries;
